### ISSUE TITLE
The very bottom element is not completely visible

### ISSUE THREAD

**Issue by Footmau** [xeurun/periodic-table-of-expressions#12]
![image](https://user-images.githubusercontent.com/5335629/185368453-231d670e-d6c4-4be0-9ed0-7bd35dfccf3a.png)

Workaround: scroll down while element is expanded.

Please add bottom page padding.

**Comment by vladimir-skorokhodov** [comment]
The issue is still reproduses, the https://github.com/xeurun/periodic-table-of-expressions/pull/13 doent fix.
